name: autofix.ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  autofix:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint --fix

      - uses: autofix-ci/action@ea32e3a12414e6d3183163c3424a7d7a8631ad84
